package ecosystem.dialogs;

import static ecosystem.Ecosystem.*;
import ecosystem.academic.Professor;
import ecosystem.components.EcosystemDialog;
import ecosystem.util.FormValidator;
import ecosystem.util.RegexValidator;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

public class AddProfessorDialog extends EcosystemDialog {
    private FormValidator validator;
    private JButton submitButton;
    private String initialId = null;
    private Professor currentProfessor = null;

    public AddProfessorDialog(JFrame parent, String initialId) {
        super(parent, true, 400, 200);
        initComponents();

        if (initialId != null) {
            this.initialId = initialId;
            this.currentProfessor = (Professor) professorManager.get(initialId);
            loadProfessorData();
            jButtonAdd.setVisible(false);
            jButtonUpdate.setVisible(true);
            submitButton = jButtonUpdate;
        } else {
            jButtonAdd.setVisible(true);
            jButtonUpdate.setVisible(false);
            submitButton = jButtonAdd;
        }

        initValidator();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int width = this.getWidth(), height = this.getHeight();
        setLocation(dim.width/2 - width/2, dim.height/2 - height/2);
        setVisible(true);
    }

    public AddProfessorDialog(JFrame parent) {
        this(parent, null);
    }

    private void loadProfessorData() {
        jTextFieldProfessorId.setText(currentProfessor.getId());
        jTextFieldLname.setText(currentProfessor.getLname());
        jTextFieldLname.setCaretPosition(0);
        jTextFieldFname.setText(currentProfessor.getFname());
        jTextFieldFname.setCaretPosition(0);
    }

    private void initValidator() {
        JTextComponent[] fields = { jTextFieldProfessorId, jTextFieldLname, jTextFieldFname };
        jTextFieldProfessorId.putClientProperty("validator", RegexValidator.NUMBER_VALIDATOR);
        jTextFieldLname.putClientProperty("validator", RegexValidator.ALPHA_VALIDATOR);
        jTextFieldFname.putClientProperty("validator", RegexValidator.ALPHA_VALIDATOR);

        for (JTextComponent jtc : fields)
            jtc.putClientProperty("required", true);

        validator = new FormValidator(fields, submitButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelIdStatic = new javax.swing.JLabel();
        jTextFieldProfessorId = new javax.swing.JTextField();
        jLabelLnameStatic = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabelFnameStatic = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 200));

        jPanelMain.setBackground(new java.awt.Color(58, 155, 83));
        jPanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMain.setPreferredSize(new java.awt.Dimension(360, 200));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIdStatic.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelIdStatic.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIdStatic.setText("Cédula");
        jPanelMain.add(jLabelIdStatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, -1, -1));

        jTextFieldProfessorId.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldProfessorId.setForeground(new java.awt.Color(34, 49, 63));
        jTextFieldProfessorId.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelMain.add(jTextFieldProfessorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 140, -1));

        jLabelLnameStatic.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelLnameStatic.setForeground(new java.awt.Color(240, 240, 240));
        jLabelLnameStatic.setText("Apellidos");
        jPanelMain.add(jLabelLnameStatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldLname.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldLname.setForeground(new java.awt.Color(34, 49, 63));
        jTextFieldLname.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelMain.add(jTextFieldLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, 240, -1));

        jLabelFnameStatic.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelFnameStatic.setForeground(new java.awt.Color(240, 240, 240));
        jLabelFnameStatic.setText("Nombres");
        jPanelMain.add(jLabelFnameStatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 105, -1, -1));

        jTextFieldFname.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldFname.setForeground(new java.awt.Color(34, 49, 63));
        jTextFieldFname.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelMain.add(jTextFieldFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, -1));

        jButtonAdd.setBackground(new java.awt.Color(231, 231, 231));
        jButtonAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(21, 25, 28));
        jButtonAdd.setText("Añadir");
        jButtonAdd.setBorder(null);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAdd.setFocusPainted(false);
        jButtonAdd.setFocusable(false);
        jButtonAdd.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 150, -1, -1));

        jButtonUpdate.setBackground(new java.awt.Color(231, 231, 231));
        jButtonUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(21, 25, 28));
        jButtonUpdate.setText("Actualizar");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonUpdate.setFocusPainted(false);
        jButtonUpdate.setFocusable(false);
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 150, -1, -1));

        jButtonCancel.setBackground(new java.awt.Color(231, 231, 231));
        jButtonCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(21, 25, 28));
        jButtonCancel.setText("Cancelar");
        jButtonCancel.setBorder(null);
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if (!validator.validateForm())
           return;
        Professor p = new Professor(jTextFieldProfessorId.getText(), jTextFieldLname.getText(), jTextFieldFname.getText());
        if (!professorManager.add(p))
            JOptionPane.showMessageDialog(null, "El docente ya se encuentra registrado", "Error", JOptionPane.ERROR_MESSAGE);
        else
            this.dispose();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        if (!validator.validateForm())
           return;

        String newId = jTextFieldProfessorId.getText();
        if (!newId.equals(initialId) && !professorManager.updateEntry(currentProfessor, newId, false)) {
            JOptionPane.showMessageDialog(this, "El docente ya se encuentra registrado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        currentProfessor.setLname(jTextFieldLname.getText());
        currentProfessor.setFname(jTextFieldFname.getText());
        professorManager.update();
        subjectManager.updateProfessor(initialId, newId);
        this.dispose();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            AddProfessorDialog dialog = new AddProfessorDialog(new javax.swing.JFrame());
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabelFnameStatic;
    private javax.swing.JLabel jLabelIdStatic;
    private javax.swing.JLabel jLabelLnameStatic;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldProfessorId;
    // End of variables declaration//GEN-END:variables
}