package ecosystem.dialogs;

import static ecosystem.Ecosystem.*;
import ecosystem.academic.Professor;
import ecosystem.academic.Subject;
import ecosystem.components.EcosystemDialog;
import ecosystem.user.Student;
import ecosystem.util.FormValidator;
import ecosystem.util.RegexValidator;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

public class AddSubjectDialog extends EcosystemDialog {
    private FormValidator validator;
    private JButton submitButton;
    private String initialId = null;
    private Subject currentSubject = null;

    public AddSubjectDialog(JFrame parent, String initialId) {
        super(parent, true);
        initComponents();

        if (initialId != null) {
            this.initialId = initialId;
            this.currentSubject = (Subject) subjectManager.get(initialId);
            jButtonAdd.setVisible(false);
            jButtonUpdate.setVisible(true);
            submitButton = jButtonUpdate;
        } else {
            jButtonAdd.setVisible(true);
            jButtonUpdate.setVisible(false);
            submitButton = jButtonAdd;
        }

        loadData();
        initValidator();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int width = this.getWidth(), height = this.getHeight();
        setLocation(dim.width/2 - width/2, dim.height/2 - height/2);
        setVisible(true);
    }

    public AddSubjectDialog(JFrame parent) {
        this(parent, null);
    }

    private void loadData() {
        for (Object o : professorManager.list) {
            Professor p = (Professor) o;
            jComboBoxProfessor.addItem(p.getId() + " " + p);

            if (currentSubject != null) {
                if (p.is(currentSubject.getProfessorId()))
                    jComboBoxProfessor.setSelectedIndex(jComboBoxProfessor.getItemCount() - 1);
            }
        }

        if (currentSubject != null) {
            jTextFieldSubjectId.setText(currentSubject.getId());
            jTextFieldName.setText(currentSubject.getName());
            jTextFieldName.setCaretPosition(0);
            jTextFieldCredits.setText(Integer.toString(currentSubject.getCredits()));
        }
    }

    private void initValidator() {
        JTextComponent[] fields = { jTextFieldSubjectId, jTextFieldName, jTextFieldCredits };
        jTextFieldSubjectId.putClientProperty("validator", RegexValidator.NUMBER_VALIDATOR);
        jTextFieldCredits.putClientProperty("validator", RegexValidator.NUMBER_VALIDATOR);

        for (JTextComponent jtc : fields)
            jtc.putClientProperty("required", true);

        validator = new FormValidator(fields, submitButton);
    }

    private String getProfessorId() {
        Object obj = professorManager.list.get(jComboBoxProfessor.getSelectedIndex());
        return ((Professor) obj).getId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelIdStatic = new javax.swing.JLabel();
        jTextFieldSubjectId = new javax.swing.JTextField();
        jLabelNameStatic = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelProfessorStatic = new javax.swing.JLabel();
        jComboBoxProfessor = new javax.swing.JComboBox<>();
        jLabelCreditsStatic = new javax.swing.JLabel();
        jTextFieldCredits = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar nueva asignatura");
        setIconImage(null);

        jPanelMain.setBackground(new java.awt.Color(58, 155, 83));
        jPanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIdStatic.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelIdStatic.setForeground(new java.awt.Color(240, 240, 240));
        jLabelIdStatic.setText("Código");
        jPanelMain.add(jLabelIdStatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 35, -1, -1));

        jTextFieldSubjectId.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldSubjectId.setForeground(new java.awt.Color(34, 49, 63));
        jTextFieldSubjectId.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelMain.add(jTextFieldSubjectId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 70, -1));

        jLabelNameStatic.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelNameStatic.setForeground(new java.awt.Color(240, 240, 240));
        jLabelNameStatic.setText("Nombre");
        jPanelMain.add(jLabelNameStatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jTextFieldName.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldName.setForeground(new java.awt.Color(34, 49, 63));
        jTextFieldName.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelMain.add(jTextFieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 65, 240, -1));

        jLabelProfessorStatic.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelProfessorStatic.setForeground(new java.awt.Color(240, 240, 240));
        jLabelProfessorStatic.setText("Docente");
        jPanelMain.add(jLabelProfessorStatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 105, -1, -1));

        jComboBoxProfessor.setBorder(null);
        jPanelMain.add(jComboBoxProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 240, -1));

        jLabelCreditsStatic.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelCreditsStatic.setForeground(new java.awt.Color(240, 240, 240));
        jLabelCreditsStatic.setText("Créditos");
        jPanelMain.add(jLabelCreditsStatic, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jTextFieldCredits.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jTextFieldCredits.setForeground(new java.awt.Color(34, 49, 63));
        jTextFieldCredits.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanelMain.add(jTextFieldCredits, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 135, 70, -1));

        jButtonAdd.setBackground(new java.awt.Color(231, 231, 231));
        jButtonAdd.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(21, 25, 28));
        jButtonAdd.setText("Añadir");
        jButtonAdd.setBorder(null);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonAdd.setFocusPainted(false);
        jButtonAdd.setFocusable(false);
        jButtonAdd.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 180, -1, -1));

        jButtonUpdate.setBackground(new java.awt.Color(231, 231, 231));
        jButtonUpdate.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(21, 25, 28));
        jButtonUpdate.setText("Actualizar");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonUpdate.setFocusPainted(false);
        jButtonUpdate.setFocusable(false);
        jButtonUpdate.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 180, -1, -1));

        jButtonCancel.setBackground(new java.awt.Color(231, 231, 231));
        jButtonCancel.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jButtonCancel.setForeground(new java.awt.Color(21, 25, 28));
        jButtonCancel.setText("Cancelar");
        jButtonCancel.setBorder(null);
        jButtonCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonCancel.setFocusPainted(false);
        jButtonCancel.setPreferredSize(new java.awt.Dimension(75, 25));
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 180, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        if (!validator.validateForm())
            return;

        String professorId = getProfessorId();
        Subject s = new Subject(jTextFieldSubjectId.getText(), jTextFieldName.getText(), professorId, Integer.valueOf(jTextFieldCredits.getText()));

        if (!subjectManager.add(s))
            JOptionPane.showMessageDialog(null, "La asignatura ya existe", "Error", JOptionPane.ERROR_MESSAGE);
        else
            this.dispose();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        String professorId = getProfessorId();
        String newId = jTextFieldSubjectId.getText();

        if (!newId.equals(initialId) && !subjectManager.updateEntry(currentSubject, newId, false)) {
            JOptionPane.showMessageDialog(this, "La asignatura ya existe", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        currentSubject.setName(jTextFieldName.getText());
        currentSubject.setProfessorId(professorId);
        currentSubject.setCredits(Integer.valueOf(jTextFieldCredits.getText()));
        subjectManager.update();

        for (String studId : currentSubject.getStudents()) {
            Student s = (Student) userManager.get(studId);
            s.updateSubject(initialId, newId);
            System.out.println(s.getAcademicData().subjects);
        }

        userManager.update();
        if (newId.equals(initialId)) {
            this.dispose();
            return;
        }

        professorManager.updateSubject(initialId, newId);
        this.dispose();
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            AddSubjectDialog dialog = new AddSubjectDialog(new javax.swing.JFrame());
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox<String> jComboBoxProfessor;
    private javax.swing.JLabel jLabelCreditsStatic;
    private javax.swing.JLabel jLabelIdStatic;
    private javax.swing.JLabel jLabelNameStatic;
    private javax.swing.JLabel jLabelProfessorStatic;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JTextField jTextFieldCredits;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldSubjectId;
    // End of variables declaration//GEN-END:variables
}
