package ecosystem;

import static ecosystem.Ecosystem.userManager;
import static ecosystem.Ecosystem.meta;
import ecosystem.user.User;
import ecosystem.user.UserType;
import ecosystem.components.EcosystemFrame;
import static ecosystem.mailing.SimpleMailApp.emailManager;
import ecosystem.user.Applicant;
import ecosystem.user.LoginResult;
import ecosystem.user.Student;
import ecosystem.util.FormValidator;
import ecosystem.util.RegexValidator;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

public class SigninFrame extends EcosystemFrame {
    private JTextComponent[] fields;
    private FormValidator signupValidator;
    private FormValidator forgotPwdValidator;

    public SigninFrame() {
        super(910, 620);
        initComponents();
        initValidationData();
        jPanelSignup.setVisible(false);
        jPanelForgotPwd.setVisible(false);
        setVisible(true);
    }

    private void initValidationData() {
        fields = new JTextComponent[] {
            jTextFieldFname,
            jTextFieldLname,
            jTextFieldEmail,
            jPasswordFieldSignup,
            jPasswordFieldConfirm
        };

        RegexValidator[] validators = new RegexValidator[] {
            RegexValidator.ALPHA_VALIDATOR,
            RegexValidator.ALPHA_VALIDATOR,
            RegexValidator.EMAIL_VALIDATOR,
            null,
            null
        };

        for (int i = 0; i < fields.length; i++) {
            JTextField field = (JTextField) fields[i];
            field.putClientProperty("validator", validators[i]);
            field.putClientProperty("required", true);
        }

        Color c1 = new Color(61, 66, 72), c2 = new Color(122, 66, 72);
        signupValidator = new FormValidator(fields, c1, c2, jButtonSignup);

        jTextFieldRenewalEmail.putClientProperty("validator", RegexValidator.EMAIL_VALIDATOR);
        jTextFieldRenewalEmail.putClientProperty("required", true);
        forgotPwdValidator = new FormValidator(new JTextComponent[] { jTextFieldRenewalEmail }, c1, c2, jButtonRequest);
    }

    private void showSignupPanel() {
        jPanelSignup.setVisible(true);
        jPanelForgotPwd.setVisible(false);
        jPanelTrademark.setVisible(false);
        repaint();
    }

    private void showTrademarkPanel() {
        jPanelSignup.setVisible(false);
        jPanelForgotPwd.setVisible(false);
        jPanelTrademark.setVisible(true);
        repaint();
    }

    private void showForgotPasswordPanel() {
        jPanelSignup.setVisible(false);
        jPanelForgotPwd.setVisible(true);
        jPanelTrademark.setVisible(false);
        repaint();
    }

    private void requestPasswordRenewal(String email) {
        User user = null;
        for (User u : userManager.list) {
            if (u instanceof Student) {
                Student s = (Student) u;
                if (!s.getEmail().equalsIgnoreCase(email))
                    continue;

                user = s;
            } else if (u instanceof Applicant) {
                Applicant a = (Applicant) u;
                if (!a.email.equalsIgnoreCase(email))
                    continue;

                user = a;
            }

            if (user != null)
                break;
        }

        if (user == null) {
            JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String newPassword = User.generatePassword();
        user.unsafeChangePassword(newPassword);
        userManager.update();
        emailManager.send("noresponder@sm.ecosystem.co", email, "Su nueva contraseña en el sistema de matrículas Ecosystem es " + newPassword);
        JOptionPane.showMessageDialog(null, "Su nueva contraseña fue enviada a su dirección de correo electrónico");
        jTextFieldRenewalEmail.setText(null);
        showTrademarkPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jLabelIcon = new javax.swing.JLabel();
        jButtonIcon = new javax.swing.JButton();
        jLabelUserIcon = new javax.swing.JLabel();
        jLabelUser = new javax.swing.JLabel();
        jTextFieldUser = new javax.swing.JTextField();
        jLabelLockIcon = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jPasswordFieldPwd = new javax.swing.JPasswordField();
        jLabelForgotPwd = new javax.swing.JLabel();
        jButtonLogin = new javax.swing.JButton();
        jButtonShowSignup = new javax.swing.JButton();
        jPanelRight = new javax.swing.JPanel();
        jPanelSignup = new javax.swing.JPanel();
        jLabelRightLogo1 = new javax.swing.JLabel();
        jLabelRightProduct1 = new javax.swing.JLabel();
        jLabelFname = new javax.swing.JLabel();
        jTextFieldFname = new javax.swing.JTextField();
        jLabelLname = new javax.swing.JLabel();
        jTextFieldLname = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelSignupPwd = new javax.swing.JLabel();
        jPasswordFieldSignup = new javax.swing.JPasswordField();
        jLabelPwdConf = new javax.swing.JLabel();
        jPasswordFieldConfirm = new javax.swing.JPasswordField();
        jButtonSignup = new javax.swing.JButton();
        jButtonSignupClose = new javax.swing.JButton();
        jPanelForgotPwd = new javax.swing.JPanel();
        jLabelRightLogo2 = new javax.swing.JLabel();
        jLabelRightProduct2 = new javax.swing.JLabel();
        jLabelRenewalEmail = new javax.swing.JLabel();
        jTextFieldRenewalEmail = new javax.swing.JTextField();
        jButtonRequest = new javax.swing.JButton();
        jButtonForgotPwdClose = new javax.swing.JButton();
        jPanelTrademark = new javax.swing.JPanel();
        jLabelTrademark = new javax.swing.JLabel();
        jLabelProduct = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanelMain.setForeground(new java.awt.Color(255, 255, 255));
        jPanelMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/check.png"))); // NOI18N
        jPanelMain.add(jLabelIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 60, -1, -1));

        jButtonIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letter.png"))); // NOI18N
        jButtonIcon.setToolTipText("Email");
        jButtonIcon.setBorder(null);
        jButtonIcon.setBorderPainted(false);
        jButtonIcon.setContentAreaFilled(false);
        jButtonIcon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/letter-active.png"))); // NOI18N
        jPanelMain.add(jButtonIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 28));

        jLabelUserIcon.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelUserIcon.setForeground(new java.awt.Color(44, 130, 201));
        jLabelUserIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile.png"))); // NOI18N
        jPanelMain.add(jLabelUserIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 203, -1, 45));

        jLabelUser.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelUser.setForeground(new java.awt.Color(44, 201, 130));
        jLabelUser.setText("Usuario");
        jPanelMain.add(jLabelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 180, -1, -1));

        jTextFieldUser.setBackground(new java.awt.Color(31, 36, 42));
        jTextFieldUser.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextFieldUser.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextFieldUser.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldUser.setNextFocusableComponent(jPasswordFieldPwd);
        jTextFieldUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUserActionPerformed(evt);
            }
        });
        jPanelMain.add(jTextFieldUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 205, 260, 40));

        jLabelLockIcon.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelLockIcon.setForeground(new java.awt.Color(169, 224, 49));
        jLabelLockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/padlock.png"))); // NOI18N
        jPanelMain.add(jLabelLockIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 300, -1, 45));

        jLabelPassword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(44, 201, 130));
        jLabelPassword.setText("Contraseña");
        jPanelMain.add(jLabelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 280, -1, -1));

        jPasswordFieldPwd.setBackground(new java.awt.Color(31, 36, 42));
        jPasswordFieldPwd.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPasswordFieldPwd.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldPwd.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPasswordFieldPwd.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordFieldPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPwdActionPerformed(evt);
            }
        });
        jPanelMain.add(jPasswordFieldPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 305, 260, 40));

        jLabelForgotPwd.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelForgotPwd.setForeground(new java.awt.Color(44, 201, 130));
        jLabelForgotPwd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelForgotPwd.setText("¿Olvidó su contraseña?");
        jLabelForgotPwd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelForgotPwdMouseClicked(evt);
            }
        });
        jPanelMain.add(jLabelForgotPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 370, -1, -1));

        jButtonLogin.setBackground(new java.awt.Color(31, 36, 42));
        jButtonLogin.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(231, 231, 231));
        jButtonLogin.setText("Entrar");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.setFocusPainted(false);
        jButtonLogin.setFocusable(false);
        jButtonLogin.setRequestFocusEnabled(false);
        jButtonLogin.setRolloverEnabled(false);
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 420, 260, 40));

        jButtonShowSignup.setBackground(new java.awt.Color(44, 130, 201));
        jButtonShowSignup.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButtonShowSignup.setForeground(new java.awt.Color(44, 201, 130));
        jButtonShowSignup.setText("Regístrese");
        jButtonShowSignup.setBorder(null);
        jButtonShowSignup.setBorderPainted(false);
        jButtonShowSignup.setContentAreaFilled(false);
        jButtonShowSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonShowSignup.setRequestFocusEnabled(false);
        jButtonShowSignup.setVerifyInputWhenFocusTarget(false);
        jButtonShowSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowSignupActionPerformed(evt);
            }
        });
        jPanelMain.add(jButtonShowSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, -1, -1));

        jPanelRight.setBackground(new java.awt.Color(46, 49, 49));
        jPanelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelSignup.setBackground(new java.awt.Color(46, 49, 49));
        jPanelSignup.setPreferredSize(new java.awt.Dimension(455, 543));
        jPanelSignup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRightLogo1.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelRightLogo1.setForeground(new java.awt.Color(44, 201, 130));
        jLabelRightLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passed-exam.png"))); // NOI18N
        jLabelRightLogo1.setText("EcoSystem");
        jPanelSignup.add(jLabelRightLogo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 10, -1, -1));

        jLabelRightProduct1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelRightProduct1.setForeground(new java.awt.Color(44, 201, 130));
        jLabelRightProduct1.setText("Sistema de matriculas");
        jPanelSignup.add(jLabelRightProduct1, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 80, -1, -1));
        jLabelRightProduct1.getAccessibleContext().setAccessibleName("Sistema de Matriculas");

        jLabelFname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelFname.setForeground(new java.awt.Color(44, 201, 130));
        jLabelFname.setText("Nombres");
        jPanelSignup.add(jLabelFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 150, -1, -1));

        jTextFieldFname.setBackground(new java.awt.Color(61, 66, 72));
        jTextFieldFname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextFieldFname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldFname.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextFieldFname.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldFname.setNextFocusableComponent(jTextFieldLname);
        jPanelSignup.add(jTextFieldFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 170, 155, 40));

        jLabelLname.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelLname.setForeground(new java.awt.Color(44, 201, 130));
        jLabelLname.setText("Apellidos");
        jPanelSignup.add(jLabelLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 150, -1, -1));

        jTextFieldLname.setBackground(new java.awt.Color(61, 66, 72));
        jTextFieldLname.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextFieldLname.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldLname.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextFieldLname.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldLname.setNextFocusableComponent(jTextFieldEmail);
        jPanelSignup.add(jTextFieldLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 170, 155, 40));

        jLabelEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(44, 201, 130));
        jLabelEmail.setText("E-mail");
        jPanelSignup.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 230, -1, -1));

        jTextFieldEmail.setBackground(new java.awt.Color(61, 66, 72));
        jTextFieldEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextFieldEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextFieldEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldEmail.setNextFocusableComponent(jPasswordFieldSignup);
        jPanelSignup.add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 250, 330, 40));

        jLabelSignupPwd.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelSignupPwd.setForeground(new java.awt.Color(44, 201, 130));
        jLabelSignupPwd.setText("Contraseña");
        jPanelSignup.add(jLabelSignupPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 300, -1, -1));

        jPasswordFieldSignup.setBackground(new java.awt.Color(61, 66, 72));
        jPasswordFieldSignup.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPasswordFieldSignup.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPasswordFieldSignup.setCaretColor(new java.awt.Color(255, 255, 255));
        jPasswordFieldSignup.setNextFocusableComponent(jPasswordFieldConfirm);
        jPanelSignup.add(jPasswordFieldSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 320, 330, 40));

        jLabelPwdConf.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelPwdConf.setForeground(new java.awt.Color(44, 201, 130));
        jLabelPwdConf.setText("Confirme su contraseña");
        jPanelSignup.add(jLabelPwdConf, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 370, -1, -1));

        jPasswordFieldConfirm.setBackground(new java.awt.Color(61, 66, 72));
        jPasswordFieldConfirm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jPasswordFieldConfirm.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldConfirm.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPasswordFieldConfirm.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanelSignup.add(jPasswordFieldConfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 390, 330, 40));

        jButtonSignup.setBackground(new java.awt.Color(44, 201, 130));
        jButtonSignup.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonSignup.setForeground(new java.awt.Color(21, 25, 28));
        jButtonSignup.setText("Solicitar registro");
        jButtonSignup.setBorder(null);
        jButtonSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSignup.setFocusPainted(false);
        jButtonSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignupActionPerformed(evt);
            }
        });
        jPanelSignup.add(jButtonSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 450, 330, 40));

        jButtonSignupClose.setBackground(new java.awt.Color(44, 130, 201));
        jButtonSignupClose.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonSignupClose.setForeground(new java.awt.Color(44, 201, 130));
        jButtonSignupClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButtonSignupClose.setText("Salir");
        jButtonSignupClose.setBorder(null);
        jButtonSignupClose.setContentAreaFilled(false);
        jButtonSignupClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonSignupClose.setIconTextGap(10);
        jButtonSignupClose.setRequestFocusEnabled(false);
        jButtonSignupClose.setVerifyInputWhenFocusTarget(false);
        jButtonSignupClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSignupCloseActionPerformed(evt);
            }
        });
        jPanelSignup.add(jButtonSignupClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 510, -1, -1));

        jPanelRight.add(jPanelSignup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanelForgotPwd.setBackground(new java.awt.Color(46, 49, 49));
        jPanelForgotPwd.setPreferredSize(new java.awt.Dimension(455, 543));
        jPanelForgotPwd.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelRightLogo2.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelRightLogo2.setForeground(new java.awt.Color(44, 201, 130));
        jLabelRightLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passed-exam.png"))); // NOI18N
        jLabelRightLogo2.setText("EcoSystem");
        jPanelForgotPwd.add(jLabelRightLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 60, -1, -1));

        jLabelRightProduct2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabelRightProduct2.setForeground(new java.awt.Color(44, 201, 130));
        jLabelRightProduct2.setText("Sistema de matriculas");
        jPanelForgotPwd.add(jLabelRightProduct2, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 130, -1, -1));

        jLabelRenewalEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jLabelRenewalEmail.setForeground(new java.awt.Color(44, 201, 130));
        jLabelRenewalEmail.setText("E-mail");
        jPanelForgotPwd.add(jLabelRenewalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 190, -1, -1));

        jTextFieldRenewalEmail.setBackground(new java.awt.Color(61, 66, 72));
        jTextFieldRenewalEmail.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextFieldRenewalEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTextFieldRenewalEmail.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jTextFieldRenewalEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        jTextFieldRenewalEmail.setNextFocusableComponent(jPasswordFieldSignup);
        jPanelForgotPwd.add(jTextFieldRenewalEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 210, 330, 40));

        jButtonRequest.setBackground(new java.awt.Color(44, 201, 130));
        jButtonRequest.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jButtonRequest.setForeground(new java.awt.Color(21, 25, 28));
        jButtonRequest.setText("Solicitar nueva constraseña");
        jButtonRequest.setBorder(null);
        jButtonRequest.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonRequest.setFocusPainted(false);
        jButtonRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRequestActionPerformed(evt);
            }
        });
        jPanelForgotPwd.add(jButtonRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 275, 330, 40));

        jButtonForgotPwdClose.setBackground(new java.awt.Color(44, 130, 201));
        jButtonForgotPwdClose.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButtonForgotPwdClose.setForeground(new java.awt.Color(44, 201, 130));
        jButtonForgotPwdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        jButtonForgotPwdClose.setText("Salir");
        jButtonForgotPwdClose.setBorder(null);
        jButtonForgotPwdClose.setContentAreaFilled(false);
        jButtonForgotPwdClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonForgotPwdClose.setIconTextGap(10);
        jButtonForgotPwdClose.setRequestFocusEnabled(false);
        jButtonForgotPwdClose.setVerifyInputWhenFocusTarget(false);
        jButtonForgotPwdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForgotPwdCloseActionPerformed(evt);
            }
        });
        jPanelForgotPwd.add(jButtonForgotPwdClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 335, -1, -1));

        jPanelRight.add(jPanelForgotPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        jPanelTrademark.setBackground(new java.awt.Color(46, 49, 49));
        jPanelTrademark.setPreferredSize(new java.awt.Dimension(455, 620));
        jPanelTrademark.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTrademark.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelTrademark.setForeground(new java.awt.Color(44, 201, 130));
        jLabelTrademark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/passed-exam.png"))); // NOI18N
        jLabelTrademark.setText("EcoSystem");
        jPanelTrademark.add(jLabelTrademark, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 200, -1, -1));

        jLabelProduct.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabelProduct.setForeground(new java.awt.Color(44, 201, 130));
        jLabelProduct.setText("Sistema de matriculas");
        jPanelTrademark.add(jLabelProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 310, -1, -1));

        jPanelRight.add(jPanelTrademark, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, -1, -1));

        jPanelMain.add(jPanelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 0, 455, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowSignupActionPerformed
        showSignupPanel();
    }//GEN-LAST:event_jButtonShowSignupActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String username = jTextFieldUser.getText();
        String pass = String.valueOf(jPasswordFieldPwd.getPassword());
        LoginResult result = userManager.login(username, pass);

        if (result == LoginResult.NO_SUCH_USER)
            JOptionPane.showMessageDialog(null, "El usuario no se encuentra registrado", "Ecosystem", JOptionPane.ERROR_MESSAGE);
        else if (result == LoginResult.WRONG_PASSWORD)
            JOptionPane.showMessageDialog(null, "Credenciales incorrectas", "Ecosystem", JOptionPane.WARNING_MESSAGE);

        if (result != LoginResult.SUCCESS)
            return;

        User user = userManager.getCurrentUser();
        if (user.type == UserType.ADMIN)
            new AdminFrame();
        else if (user.type == UserType.GENERIC)
            new StudentFrame();

        this.dispose();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignupActionPerformed
        if (!signupValidator.validateForm())
            return;

        String fname = jTextFieldFname.getText();
        String lname = jTextFieldLname.getText();
        String email = jTextFieldEmail.getText();
        String password = String.valueOf(jPasswordFieldSignup.getPassword());
        String pwdConfirm = String.valueOf(jPasswordFieldConfirm.getPassword());

        if (!password.equals(pwdConfirm)) {
            JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden, por favor verifique", "Ecosystem", JOptionPane.ERROR_MESSAGE);
            signupValidator.focus(jPasswordFieldSignup);
            return;
        }

        Applicant user = new Applicant(email, password, fname, lname);
        if (!userManager.add(user)) {
            JOptionPane.showMessageDialog(null, "El usuario ya se encuentra registrado", "Ecosystem", JOptionPane.ERROR_MESSAGE);
            signupValidator.focus(jTextFieldEmail);
            return;
        }

        Object requestCountObj = meta.getItem("requestCount");
        if (requestCountObj == null)
            meta.setItem("requestCount", 1);
        else
            meta.setItem("requestCount", ((int) requestCountObj) + 1);

        JOptionPane.showMessageDialog(null, "Usuario registrado satisfactoriamente, debe iniciar sesión para verificar su identidad", "Ecosystem", JOptionPane.INFORMATION_MESSAGE);
        showTrademarkPanel();
        signupValidator.clear();
    }//GEN-LAST:event_jButtonSignupActionPerformed

    private void jTextFieldUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUserActionPerformed
        jButtonLogin.doClick();
    }//GEN-LAST:event_jTextFieldUserActionPerformed

    private void jPasswordFieldPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPwdActionPerformed
        jButtonLogin.doClick();
    }//GEN-LAST:event_jPasswordFieldPwdActionPerformed

    private void jButtonSignupCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSignupCloseActionPerformed
        showTrademarkPanel();
    }//GEN-LAST:event_jButtonSignupCloseActionPerformed

    private void jLabelForgotPwdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelForgotPwdMouseClicked
        showForgotPasswordPanel();
    }//GEN-LAST:event_jLabelForgotPwdMouseClicked

    private void jButtonForgotPwdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForgotPwdCloseActionPerformed
        showTrademarkPanel();
    }//GEN-LAST:event_jButtonForgotPwdCloseActionPerformed

    private void jButtonRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRequestActionPerformed
        if (!forgotPwdValidator.validateForm())
            return;

        requestPasswordRenewal(jTextFieldRenewalEmail.getText());
    }//GEN-LAST:event_jButtonRequestActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new SigninFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForgotPwdClose;
    private javax.swing.JButton jButtonIcon;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRequest;
    private javax.swing.JButton jButtonShowSignup;
    private javax.swing.JButton jButtonSignup;
    private javax.swing.JButton jButtonSignupClose;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFname;
    private javax.swing.JLabel jLabelForgotPwd;
    private javax.swing.JLabel jLabelIcon;
    private javax.swing.JLabel jLabelLname;
    private javax.swing.JLabel jLabelLockIcon;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelProduct;
    private javax.swing.JLabel jLabelPwdConf;
    private javax.swing.JLabel jLabelRenewalEmail;
    private javax.swing.JLabel jLabelRightLogo1;
    private javax.swing.JLabel jLabelRightLogo2;
    private javax.swing.JLabel jLabelRightProduct1;
    private javax.swing.JLabel jLabelRightProduct2;
    private javax.swing.JLabel jLabelSignupPwd;
    private javax.swing.JLabel jLabelTrademark;
    private javax.swing.JLabel jLabelUser;
    private javax.swing.JLabel jLabelUserIcon;
    private javax.swing.JPanel jPanelForgotPwd;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelRight;
    private javax.swing.JPanel jPanelSignup;
    private javax.swing.JPanel jPanelTrademark;
    private javax.swing.JPasswordField jPasswordFieldConfirm;
    private javax.swing.JPasswordField jPasswordFieldPwd;
    private javax.swing.JPasswordField jPasswordFieldSignup;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFname;
    private javax.swing.JTextField jTextFieldLname;
    private javax.swing.JTextField jTextFieldRenewalEmail;
    private javax.swing.JTextField jTextFieldUser;
    // End of variables declaration//GEN-END:variables
}
